# model
ckpt_dir: ./ckpts
ckpt_name: Ovi/model.safetensors

# face embedder 
face_embedder_ckpt_dir: ./ckpts/InsightFace
face_ip_emb_dim: 512
# audio embedder, TODO
audio_embedder_ckpt_dir: ../weights/naturalspeech3_facodec
audio_ip_emb_dim: 256
# asr model
glm_asr_ckpt_path: ./ckpts/GLM_ASR/GLM-ASR-Nano-2512
max_new_tokens: 128
# vae
height_division_factor: 16
width_division_factor: 16
time_division_factor: 4
time_division_remainder: 1

cpu_offload: False
self_lora: True #True False
use_contrastive: True
contrastive_weight: 0.1
contrastive_cutoff: 0.2
time_shift: 5
use_sp: False
sp_size: 1
trainable_models: "q_loras,k_loras,v_loras,o_loras,s_q_loras,s_k_loras,s_v_loras,s_o_loras,ip_embedding,ip_projection"